Trailhead/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales - Branch Managers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales - Branch RMs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales - District Managers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales - Investment Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wealth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>WAM_Distributor</fullName>
        <active>true</active>
        <description>Record type for WAM CRM Distributors</description>
        <label>WAM Distributor</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Trailhead/src/objects/Contact_Purpose__c.object
<CustomObject>
    <description>ATO&apos;s Initiatives to standardize the Salesforce Architecture</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Purposes</relationshipLabel>
        <relationshipName>Contact_Purposes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Method_Type__c</fullName>
        <label>Contact Method Type</label>
        <picklist>
            <picklistValues>
                <fullName>Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WebPage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InPerson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <label>Contact Purpose</label>
        <picklist>
            <picklistValues>
                <fullName>Fund Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Document</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales - Branch Managers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales - Branch RMs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales - District Managers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales - Investment Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wealth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contact Purpose</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Contact Purpose ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Purposes</pluralLabel>
    <recordTypes>
        <fullName>WAM</fullName>
        <active>true</active>
        <label>WAM</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WAM_CustomSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>WAMCRM: custom Settings</description>
    <fields>
        <fullName>AUM_in_Manulife_Record_Type__c</fullName>
        <description>WAMCRM : AUM in Manulife Record Type</description>
        <inlineHelpText>WAMCRM : AUM in Manulife Record Type</inlineHelpText>
        <label>AUM in Manulife Record Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Distributor_Record_Type_Label__c</fullName>
        <label>Account Distributor Record Type Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Distributor_Record_Type_Name__c</fullName>
        <label>Account Distributor Record Type Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Distributor_Record_Type_Label__c</fullName>
        <description>WAMCRM : Contact Distributor Record Type Label</description>
        <inlineHelpText>WAMCRM : Contact Distributor Record Type Label</inlineHelpText>
        <label>Contact Distributor Record Type Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Distributor_Record_Type_Name__c</fullName>
        <description>WAMCRM : Contact Distributor Record Type Name</description>
        <inlineHelpText>WAMCRM : Contact Distributor Record Type Name</inlineHelpText>
        <label>Contact Distributor Record Type Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Purpose_Record_Type_Label__c</fullName>
        <label>Contact Purpose Record Type Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Country_Code__c</fullName>
        <description>WAMCRM: Default country code</description>
        <inlineHelpText>WAMCRM: Default country code</inlineHelpText>
        <label>Default Country Code</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distributor_Sales_Info_Record_Type__c</fullName>
        <description>WAMCRM : Distributor Sales InformationRecord Type</description>
        <inlineHelpText>WAMCRM : Distributor Sales InformationRecord Type</inlineHelpText>
        <label>Distributor Sales Info Record Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Record_Type__c</fullName>
        <description>WAMCRM : Event Record Type used to manage distributors</description>
        <inlineHelpText>WAMCRM : Event Record Type used to manage distributors</inlineHelpText>
        <label>Event Record Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fund_Record_Type__c</fullName>
        <description>WAMCRM : Fund Record Type to distinguish WAM funds</description>
        <inlineHelpText>WAMCRM : Fund Record Type to distinguish WAM funds</inlineHelpText>
        <label>Fund Record Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Distributor_Record_Type__c</fullName>
        <description>WAMCRM : Opportunity Distributor Record Type</description>
        <inlineHelpText>WAMCRM : Opportunity Distributor Record Type</inlineHelpText>
        <label>Opportunity Distributor Record Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Record_Type__c</fullName>
        <description>WAMCRM : Task Record Type to manage distributors</description>
        <inlineHelpText>WAMCRM : Task Record Type to manage distributors</inlineHelpText>
        <label>Task Record Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>WAM_CustomSetting</label>
</CustomObject>

src/classes/WAM_CodeCoverageDataFactory.cls
/* 
* WAM_CodeCoverageDataFactory 
* Date / Author / Description
* 
* 10-May / ONGFT / To generate WAM mock data.
* 
*/

@IsTest
public class WAM_CodeCoverageDataFactory {

    public WAM_CodeCoverageDataFactory() {}

    public static void initDocumentOptOutData() {
        initAccountAndContacts();
    }  

    public static String testUserName = 'wamusertest@manulife.com.japan.wamtest';
    
    /**
    * Create Test Data for Distributor with Contacts
    *
    * @return void
    * 
    */
    private static void initAccountAndContacts() {

        Profile p = [SELECT Id FROM Profile WHERE Name='WAM Partnership Distribution'];
        User u2 = new User(Alias = 'wamuser', Email='wamusertest@manulife.com',
            EmailEncodingKey='UTF-8', LastName='wamuser', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName=WAM_CodeCoverageDataFactory.testUserName);

        insert u2;   
        
        WAM_CustomSetting__c settings = WAM_CustomSetting__c.getOrgDefaults();
        settings.Account_Distributor_Record_Type_Name__c = 'WAM_Distributor';
        settings.Account_Distributor_Record_Type_Label__c = 'WAM Distributor';      
        settings.Contact_Distributor_Record_Type_Name__c = 'WAM_Distributor';
        settings.Contact_Distributor_Record_Type_Label__c = 'WAM Distributor';
        settings.AUM_in_Manulife_Record_Type__c = 'WAM';
        settings.Distributor_Sales_Info_Record_Type__c = 'WAM';
        settings.Event_Record_Type__c = 'WAMEventRT';
        settings.Fund_Record_Type__c = 'WAM';
        settings.Opportunity_Distributor_Record_Type__c = 'WAM';
        settings.Task_Record_Type__c = 'WAM';
        settings.Contact_Purpose_Record_Type_Label__c = 'WAM';
        settings.Default_Country_Code__c = '+(81)';

        upsert settings;

        String contactWAMId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(WAM_CustomSetting__c.getInstance().Contact_Distributor_Record_Type_Label__c).getRecordTypeId();
        String wamContactPurposeRecordTypeId = Schema.SObjectType.Contact_Purpose__c.getRecordTypeInfosByName().get(WAM_CustomSetting__c.getInstance().Contact_Purpose_Record_Type_Label__c).getRecordTypeId();

        System.runAs(u2){
            Account acc = new Account(Name = 'TestAccount');
            insert acc;
            
            Account noDataAcc = new Account(Name = 'TestAccount1');
            insert noDataAcc;
            
            List<Contact_Purpose__c> contactPurposeList = new List<Contact_Purpose__c>();
            Contact_Purpose__c cp = new Contact_Purpose__c();    
            cp.Contact_Method_Type__c = 'Email';                    
            cp.Purpose__c = 'Fund Information';
            cp.Role__c = 'Product';   
            cp.Account__c = acc.Id;
            cp.RecordTypeId = wamContactPurposeRecordTypeId;
            contactPurposeList.add(cp); 
            
            cp = new Contact_Purpose__c();  
            cp.Contact_Method_Type__c = 'Email';                    
            cp.Purpose__c = 'Market Information';
            cp.Role__c = 'Product';   
            cp.Account__c = acc.Id;
            cp.RecordTypeId = wamContactPurposeRecordTypeId;
            contactPurposeList.add(cp); 
            
            cp = new Contact_Purpose__c();    
            cp.Contact_Method_Type__c = 'Email';                    
            cp.Purpose__c = 'Market Information';
            cp.Role__c = 'Compliance';   
            cp.Account__c = acc.Id;
            cp.RecordTypeId = wamContactPurposeRecordTypeId;
            contactPurposeList.add(cp); 
            
            cp = new Contact_Purpose__c();    
            cp.Contact_Method_Type__c = 'Email';                    
            cp.Purpose__c = 'Event Promotion';
            cp.Role__c = 'Wealth';   
            cp.Account__c = acc.Id;
            cp.RecordTypeId = wamContactPurposeRecordTypeId;
            contactPurposeList.add(cp); 
            
            cp = new Contact_Purpose__c();    
            cp.Contact_Method_Type__c = 'Email';                    
            cp.Purpose__c = 'Legal Document';
            cp.Role__c = 'Senior Management';   
            cp.Account__c = acc.Id;
            cp.RecordTypeId = wamContactPurposeRecordTypeId;
            contactPurposeList.add(cp); 
            
            insert contactPurposeList;
                
            List<Contact> conList = new List<Contact>();
            integer i = 1;
            for (String role : WAM_UtilityClass.getRoleList){
                
                Contact con = new Contact(FirstName='FName_'+role, AccountId=acc.Id, LastName='LName', 
                                          Email='wamtest'+i+'@manulife.com', Title=role, Role__c=role, RecordTypeID=contactWAMId);
                conList.add(con);
                i++;
                
            }
            System.debug('conList: ' + conList );
            insert conList;
        }
    }
}