Trailhead/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales - Branch Managers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales - Branch RMs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales - District Managers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales - Investment Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wealth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Trailhead/src/objects/Contact_Purpose__c.object
<CustomObject>
    <description>ATO&apos;s Initiatives to standardize the Salesforce Architecture</description>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales - Branch Managers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales - Branch RMs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales - District Managers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales - Investment Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wealth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contact Purpose</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Contact Purpose ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Purposes</pluralLabel>
    <recordTypes>
        <fullName>WAM</fullName>
        <active>true</active>
        <label>WAM</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WAM_CustomSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>WAMCRM: custom Settings</description>
    <fields>
        <fullName>Contact_Distributor_Record_Type_Label__c</fullName>
        <description>WAMCRM : Contact Distributor Record Type Label</description>
        <inlineHelpText>WAMCRM : Contact Distributor Record Type Label</inlineHelpText>
        <label>Contact Distributor Record Type Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Purpose_Record_Type_Label__c</fullName>
        <label>Contact Purpose Record Type Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>WAM_CustomSetting</label>
</CustomObject>

src/objects/WAM_Document_Opt_Out_Mapper__mdt.object
<CustomObject>
    <description>WAMCRM: Mapping individual document at contact into Document category.</description>
    <fields>
        <fullName>Contact_Level_API__c</fullName>
        <label>Contact Level API</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Category__c</fullName>
        <label>Document Category</label>
        <picklist>
            <picklistValues>
                <fullName>Fund Information</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Market Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Document</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>WAM Document Opt Out Mapper</label>
    <pluralLabel>WAM Document Opt Out Mappers</pluralLabel>
</CustomObject>

src/classes/WAM_UtilityClass.cls
/*
* WAM_UtilityClass 
* Date / Author / Description
* 
* 30-Jan / TANSH/ Util for WAM
*/
public class WAM_UtilityClass {
    
    public static String wamContactRecordTypeId {
        get {
            return Schema.SObjectType.Contact.getRecordTypeInfosByName().get(WAM_CustomSetting__c.getInstance().Contact_Distributor_Record_Type_Label__c).getRecordTypeId();
        }
        set;
    }
    
    public static String wamContactPurposeRecordTypeId {
        get {
            return Schema.SObjectType.Contact_Purpose__c.getRecordTypeInfosByName().get(WAM_CustomSetting__c.getInstance().Contact_Purpose_Record_Type_Label__c).getRecordTypeId();
        }
        set;
    }
    
    public static List<String> getRoleList {
        get {
                List<String> lroleList = new List<String>();
                for (Schema.PicklistEntry a : Schema.getGlobalDescribe().get('Contact_Purpose__c').getDescribe().fields.getMap().get('Role__c').getDescribe().getPickListValues()) { 
                    lroleList.add(a.getValue());
                }
            return lroleList;           
        }
        set;
    }
    
    public static Map<String, String> getFieldMapper() {
        Map<String, String> fieldMapper = new Map<String, String>();
        
        for (WAM_Document_Opt_Out_Mapper__mdt rec: [SELECT Document_Category__c, Contact_Level_API__c FROM WAM_Document_Opt_Out_Mapper__mdt ORDER BY Document_Category__c]) {
            fieldMapper.put(rec.Contact_Level_API__c, rec.Document_Category__c);
        }
        
        return fieldMapper;
    }
    
    public static String exceptionStr = System.Label.WAM_UnexpectedExceptionMessage;
}